name: Build and push Docker image to GHCR

on:
  workflow_dispatch:
  release:
    branches: [ main ]
    types: [ published ]

env:
  REGISTRY: ghcr.io
  GQL_HOST: https://wg-ui.unafraid.dev/query
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            latest
          labels: |
            org.opencontainers.image.vendor="Desislav"
            org.opencontainers.image.url="https://github.com/desislavsd/wireguard-manager"
            org.opencontainers.image.title="Wireguard Manager"
            org.opencontainers.image.description="Wireguard Manager written in Vue using Nuxt3 and quasar"
            org.opencontainers.image.documentation="https://github.com/desislavsd/wireguard-manager"

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            GQL_HOST=${{ env.GQL_HOST }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
